"use client";
import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  X,
  Copy,
  Check,
  Linkedin,
  Mail,
  Zap,
  Sparkles,
  Info,
  TextQuote,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { generateOutreachDrafts } from "@/lib/api";
import { toast } from "sonner";

interface OutreachModalProps {
  isOpen: boolean;
  onClose: () => void;
  matchId: string;
  tone?: string;
}

export default function OutreachModal({
  isOpen,
  onClose,
  matchId,
  tone = "Formal",
}: OutreachModalProps) {
  const [loading, setLoading] = useState(true);
  const [drafts, setDrafts] = useState<{
    linkedin_request: string;
    cold_email: string;
    company_name?: string;
  } | null>(null);
  const [activeTab, setActiveTab] = useState<"linkedin" | "email">("linkedin");
  const [copied, setCopied] = useState(false);

  const fetchDrafts = useCallback(async () => {
    setLoading(true);
    try {
      const data = await generateOutreachDrafts(matchId, tone);
      setDrafts(data);
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate drafts");
      onClose();
    } finally {
      setLoading(false);
    }
  }, [matchId, tone, onClose]);

  useEffect(() => {
    if (isOpen && matchId) {
      fetchDrafts();
    }
  }, [isOpen, matchId, fetchDrafts]);

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-6 overflow-hidden">
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0 bg-[#1A202C]/60 backdrop-blur-xl"
      />

      <motion.div
        initial={{ opacity: 0, scale: 0.9, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.9, y: 20 }}
        className="relative w-full max-w-3xl bg-white rounded-[3rem] shadow-2xl overflow-hidden border border-[#E2E8F0]"
      >
        {/* Header */}
        <div className="p-8 md:p-12 border-b border-[#F1F5F9] flex items-center justify-between bg-linear-to-br from-white to-[#F8FAFC]">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <div className="w-6 h-6 rounded-lg bg-[#7C9ADD]/10 flex items-center justify-center">
                <Sparkles size={14} className="text-[#7C9ADD]" />
              </div>
              <span className="text-[10px] font-black uppercase tracking-[0.3em] text-[#7C9ADD]">
                AI Outreach Engine
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-display font-black text-[#1A202C] tracking-tighter">
              Outreach <span className="text-[#7C9ADD]">Drafts</span>
            </h2>
            <p className="text-sm font-medium text-[#718096]">
              Personalized high-reasoning messages generated by Hirenix AI.
            </p>
          </div>
          <button
            onClick={onClose}
            aria-label="Close modal"
            className="w-12 h-12 rounded-2xl #F1F5F9] flex items-center justify-center text-[#A0AEC0] transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        <div className="flex flex-col md:flex-row h-[500px]">
          {/* Sidebar Tabs */}
          <div className="w-full md:w-64 bg-[#F8FAFC] border-r border-[#F1F5F9] p-6 space-y-4">
            <button
              onClick={() => setActiveTab("linkedin")}
              className={`w-full p-4 rounded-2xl flex items-center gap-3 transition-all ${
                activeTab === "linkedin"
                  ? "bg-white shadow-lg text-[#0A66C2] border border-[#0A66C2]/10"
                  : "text-[#718096]"
              }`}
            >
              <Linkedin size={20} />
              <span className="text-xs font-black uppercase tracking-widest">
                LinkedIn
              </span>
            </button>
            <button
              onClick={() => setActiveTab("email")}
              className={`w-full p-4 rounded-2xl flex items-center gap-3 transition-all ${
                activeTab === "email"
                  ? "bg-white shadow-lg text-[#6366F1] border border-[#6366F1]/10"
                  : "text-[#718096]"
              }`}
            >
              <Mail size={20} />
              <span className="text-xs font-black uppercase tracking-widest">
                Cold Email
              </span>
            </button>

            <div className="mt-auto pt-8">
              <div className="p-4 rounded-2xl bg-[#7C9ADD]/5 border border-[#7C9ADD]/10 flex flex-col gap-3">
                <div className="flex items-center gap-2 text-[#7C9ADD]">
                  <Info size={14} />
                  <span className="text-[10px] font-black uppercase tracking-widest">
                    Pro Tip
                  </span>
                </div>
                <p className="text-[10px] font-bold text-[#718096] leading-relaxed italic">
                  &quot;Always double-check the recruiter&apos;s name and
                  company specifics before hitting send.&quot;
                </p>
              </div>
            </div>
          </div>

          {/* Content Area */}
          <div className="flex-1 overflow-y-auto p-8 md:p-10 relative">
            <AnimatePresence mode="wait">
              {loading ? (
                <motion.div
                  key="loading"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 flex flex-col items-center justify-center text-center p-12 space-y-6"
                >
                  <div className="relative">
                    <div className="w-16 h-16 border-4 border-[#7C9ADD]/20 border-t-[#7C9ADD] rounded-full animate-spin" />
                    <Zap
                      className="absolute inset-0 m-auto text-[#7C9ADD]"
                      size={24}
                    />
                  </div>
                  <div>
                    <h4 className="text-sm font-black uppercase tracking-widest text-[#1A202C] mb-2">
                      Reasoning with Hirenix AI
                    </h4>
                    <p className="text-xs font-medium text-[#718096]">
                      Analyzing job requirements and your professional
                      footprint...
                    </p>
                  </div>
                </motion.div>
              ) : drafts ? (
                <motion.div
                  key={activeTab}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="space-y-8"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {activeTab === "linkedin" ? (
                        <div className="w-10 h-10 rounded-xl bg-[#0A66C2]/10 text-[#0A66C2] flex items-center justify-center">
                          <Linkedin size={20} />
                        </div>
                      ) : (
                        <div className="w-10 h-10 rounded-xl bg-[#6366F1]/10 text-[#6366F1] flex items-center justify-center">
                          <Mail size={20} />
                        </div>
                      )}
                      <div>
                        <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-[#A0AEC0]">
                          Targeting: {drafts.company_name ?? "Verified Company"}
                        </h4>
                        <p className="text-sm font-bold text-[#1A202C]">
                          {activeTab === "linkedin"
                            ? "Connection Request"
                            : "Recruiter Message"}
                        </p>
                      </div>
                    </div>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="rounded-xl"
                      onClick={() =>
                        copyToClipboard(
                          activeTab === "linkedin"
                            ? drafts.linkedin_request
                            : drafts.cold_email,
                        )
                      }
                    >
                      {copied ? (
                        <Check className="text-emerald-500" size={18} />
                      ) : (
                        <Copy size={18} />
                      )}
                    </Button>
                  </div>

                  <div className="relative group">
                    <div className="absolute -top-4 -left-4 text-[#7C9ADD]/10">
                      <TextQuote size={40} />
                    </div>
                    <div className="p-8 rounded-[2rem] bg-slate-50 border border-slate-100 font-body text-sm font-medium leading-[1.8] text-[#2D3748] whitespace-pre-line selection:bg-[#7C9ADD]/20">
                      {activeTab === "linkedin"
                        ? drafts.linkedin_request
                        : drafts.cold_email}
                    </div>
                  </div>

                  {activeTab === "linkedin" &&
                    drafts.linkedin_request.length > 300 && (
                      <div className="p-4 rounded-xl bg-amber-50 border border-amber-100 flex items-start gap-3">
                        <Info size={16} className="text-amber-500 mt-0.5" />
                        <p className="text-[10px] font-bold text-amber-900 leading-relaxed">
                          Note: This request exceeds LinkedIn&apos;s
                          300-character limit. You might need to trim it
                          slightly or send it as a message if you have Premium.
                        </p>
                      </div>
                    )}
                </motion.div>
              ) : null}
            </AnimatePresence>
          </div>
        </div>

        {/* Footer info */}
        <div className="p-6 bg-[#1A202C] text-center">
          <p className="text-[9px] font-black uppercase tracking-[0.5em] text-[#7C9ADD]/60">
            Powered by Hirenix AI
          </p>
        </div>
      </motion.div>
    </div>
  );
}
